version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
